FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /app

COPY app-service-auth/pom.xml .
RUN mvn dependency:go-offline -B

COPY app-service-auth/src ./src
RUN mvn clean package -DskipTests -B

FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=builder /app/target/*.jar app-service-auth.jar

EXPOSE 8081

ENV JAVA_OPTS="-Xmx512m -Xms256m"

# Executar a aplicação
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app-service-auth.jar"]

